version: "3.7"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    environment:
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:11.2
