# Generated by Django 2.1.7 on 2019-03-25 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('not_answered', 'not_answered')], default='not_answered', max_length=20)),
                ('reason', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='employee_accepted',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='employer_accepted',
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='answer',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Proposal'),
        ),
    ]
