# Generated by Django 2.2 on 2020-01-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190703_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='positive',
            field=models.BooleanField(),
        ),
    ]
